[package]
name = "irc-twitch"
version = "0.1.0"
edition = "2021"
authors = ["Paulo Gabriel Justino Bezerra <contact@pgjbz.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1.5.6"
